site_name: zxcvbn-rs-py
site_description: zxcvbn password strength library for Python using Rust bindings

repo_url: https://github.com/fief-dev/zxcvbn-rs-py
repo_name: fief-dev/zxcvbn-rs-py

theme:
    name: material
    icon:
        logo: material/key-chain-variant
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          accent: amber
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: amber
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    features:
      - navigation.instant
      - navigation.expand
      - navigation.indexes
      - navigation.top
      - search.suggest
      - search.highlight
      - content.code.copy

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [./zxcvbn_rs_py]
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - zxcvbn_rs_py

nav:
    - About: index.md
    - Reference:
        - zxcvbn_rs_py: reference/zxcvbn_rs_py.md
